# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "REPLACE_WITH_PUBLIC_CLIENT_ID"
application_url = "https://neighborly-nightingale-843.convex.site/api/shopify/app"
embedded = true
name = "keval-test-app"

[webhooks]
api_version = "2026-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_customer_events,write_pixels"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]

[build]
automatically_update_urls_on_dev = false

[[webhooks.subscriptions]]
topics = ["app/uninstalled", "app/scopes_update"]
uri = "/api/shopify/webhooks"
