import test from 'node:test';import assert from 'node:assert/strict';
import {summarize,type CheckoutEvent} from '../shared/evidence.ts';
import {checkoutCohort} from '../shared/dateRange.ts';
import {abandonedSummary} from '../shared/abandonedSummary.ts';
import {actionValues} from '../shared/actionValues.ts';
import {recordedFindings,stepTimings} from '../shared/dashboardInsights.ts';
import {journeyDuration} from '../shared/journeyDuration.ts';
import {journeyPrice} from '../shared/journeyPrice.ts';
import {checkoutCSV,checkoutEventsCSV} from '../shared/checkoutExport.ts';
import {fixBaseline,fixResults} from '../shared/fixTracking.ts';
import {buildRecommendations} from '../shared/recommendations.ts';
const start=100000,end=200000;
let serial=0;
const e=(id:string,name:CheckoutEvent['name'],timestamp:number,category:CheckoutEvent['category']=null,blocker=false):CheckoutEvent=>({eventId:String(++serial),sessionId:id,name,timestamp,category,...(blocker?{shippingBlocker:'no_shipping_available' as const}:{})});
const events:CheckoutEvent[]=Array.from({length:78},(_,i)=>e(String(i),'checkout_started',start+1000));
for(let i=0;i<24;i++)events.push(e(String(i),'checkout_completed',start+31000));
for(let i=0;i<5;i++)events.push(e(String(i),'checkout_address_info_submitted',start+11000),e(String(i),'alert_displayed',start+12000,'validation'),e(String(i),'alert_displayed',start+13000,'validation'));
for(const id of ['24','25'])events.push(e(id,'checkout_address_info_submitted',start+11000),e(id,'alert_displayed',start+12000,'delivery',true),e(id,'alert_displayed',start+13000,'delivery',true));
const excluded=[e('before','checkout_started',start-1),e('before','checkout_completed',start+2),e('after','checkout_started',end),e('orphan','checkout_completed',start+30000)];
const records=[{recordHash:'one',sessionId:'24',createdAt:new Date(start+1).toISOString(),subtotalCents:74995,totalCents:77995,recovered:false},{recordHash:'two',sessionId:'25',createdAt:new Date(start+1).toISOString(),subtotalCents:60000,totalCents:62000,recovered:false},{recordHash:'zero',sessionId:'26',createdAt:new Date(start+1).toISOString(),subtotalCents:0,totalCents:0,recovered:false},{recordHash:'done',sessionId:'0',createdAt:new Date(start+1).toISOString(),subtotalCents:60000,totalCents:62000,recovered:true}];
test('golden dashboard totals reconcile completion, abandoned totals, recommendations, findings and evidence',()=>{
 const cohort=checkoutCohort([...events,...excluded,events[0]],{start,end}),summary=summarize(cohort);
 assert.equal(summary.sessionCount,78);assert.equal(summary.completed,24);assert.equal(summary.noCompletionObserved,54);
 assert.equal(summary.completed+summary.noCompletionObserved,summary.sessionCount);assert.equal(Math.round(summary.completed/summary.sessionCount*100),31);
 assert.equal(summary.eventCount,123);
 assert.deepEqual(abandonedSummary(records,start,end),{count:3,totalCents:139995,averageCents:46665,unpricedCount:0,rangeStart:start,rangeEnd:end});
 const recommendations=buildRecommendations(cohort);assert.equal(recommendations.length,1);assert.equal(recommendations[0].count,2);assert.equal(Math.round(2/78*100),3);
 const actions=actionValues(cohort,null,records,[],'USD',start,end);assert.equal(actions.combined.totalCents,139995);assert.equal(actions.combined.matchedSessions,2);
 assert.equal(journeyPrice('24',false,[],'USD',[],records),77995);assert.equal(journeyPrice('26',false,[],'USD',[],records),0);
 const findings=recordedFindings(cohort),form=findings.find(f=>f.category==='validation')!,shipping=findings.find(f=>f.category==='shipping_blocker')!;
 assert.equal(form.sessionIds.length,5);assert.equal(form.alerts.length,10);assert.equal(form.repeatedCheckouts,5);assert.equal(form.completedAfter,5);
 assert.equal(shipping.sessionIds.length,2);assert.equal(shipping.alerts.length,4);assert.equal(shipping.repeatedCheckouts,2);assert.equal(shipping.completedAfter,0);
});
test('duration, milestones, export counts and saved fix before/after use the same journey evidence',()=>{
 const rows=[e('timed','checkout_started',10000),e('timed','checkout_contact_info_submitted',30000),e('timed','checkout_shipping_info_submitted',60000),e('timed','checkout_completed',136000),e('timed','payment_info_submitted',140000)];
 assert.equal(journeyDuration(rows),'02:06 spent time');assert.deepEqual(stepTimings(rows).map(r=>r.seconds),[20,30,76]);
 const exportRows=[{id:'timed',label:'#123',startedAt:10000,completed:true,basketCents:139995,events:rows}];
 assert.match(checkoutCSV(exportRows,'USD'),/"1399.95","USD"/);assert.equal(checkoutEventsCSV(exportRows).split('\r\n').filter(Boolean).length,6);
 const fix=fixBaseline(events,'delivery',end);assert.deepEqual(fix.baseline,{checkouts:78,affected:2,completed:24});
 const after=[...events,e('new','checkout_started',end+10),e('new','alert_displayed',end+20,'delivery'),e('new','checkout_completed',end+30),e('24','checkout_completed',end+40)];
 assert.deepEqual(fixResults(fix,after,end+50).after,{checkouts:1,affected:1,completed:1});assert.equal(fixResults(fix,after,end+50).affectedCompleted,1);
});
